=== ThoughtfulMind/d3-foresight/examples/data-timechart.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "region": {
      "type": "string",
      "minLength": 1
    },
    "observed": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "week"
        ],
        "properties": {
          "week": {
            "type": "number"
          },
          "data": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "items": {
              "required": [
                "lag",
                "value"
              ],
              "properties": {
                "lag": {
                  "type": "number"
                },
                "value": {
                  "type": "number"
                }
              }
            }
          }
        }
      }
    },
    "actual": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "week",
          "data"
        ],
        "properties": {
          "week": {
            "type": "number"
          },
          "data": {
            "type": "number"
          }
        }
      }
    },
    "baseline": {
      "type": "number"
    },
    "models": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "meta": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "minLength": 1
              },
              "description": {
                "type": "string",
                "minLength": 1
              },
              "url": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "name",
              "description",
              "url"
            ]
          },
          "predictions": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "items": {
              "required": [
                "week"
              ],
              "properties": {
                "onsetWeek": {
                  "type": "object",
                  "properties": {
                    "point": {
                      "type": "number"
                    },
                    "low": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    },
                    "high": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    }
                  },
                  "required": [
                    "point",
                    "low",
                    "high"
                  ]
                },
                "peakWeek": {
                  "type": "object",
                  "properties": {
                    "point": {
                      "type": "number"
                    },
                    "low": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    },
                    "high": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    }
                  },
                  "required": [
                    "point",
                    "low",
                    "high"
                  ]
                },
                "peakPercent": {
                  "type": "object",
                  "properties": {
                    "point": {
                      "type": "number"
                    },
                    "low": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    },
                    "high": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    }
                  },
                  "required": [
                    "point",
                    "low",
                    "high"
                  ]
                },
                "oneWk": {
                  "type": "object",
                  "properties": {
                    "point": {
                      "type": "number"
                    },
                    "low": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    },
                    "high": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    }
                  },
                  "required": [
                    "point",
                    "low",
                    "high"
                  ]
                },
                "twoWk": {
                  "type": "object",
                  "properties": {
                    "point": {
                      "type": "number"
                    },
                    "low": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    },
                    "high": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    }
                  },
                  "required": [
                    "point",
                    "low",
                    "high"
                  ]
                },
                "threeWk": {
                  "type": "object",
                  "properties": {
                    "point": {
                      "type": "number"
                    },
                    "low": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    },
                    "high": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    }
                  },
                  "required": [
                    "point",
                    "low",
                    "high"
                  ]
                },
                "fourWk": {
                  "type": "object",
                  "properties": {
                    "point": {
                      "type": "number"
                    },
                    "low": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    },
                    "high": {
                      "type": "array",
                      "items": {
                        "required": [],
                        "properties": {}
                      }
                    }
                  },
                  "required": [
                    "point",
                    "low",
                    "high"
                  ]
                },
                "week": {
                  "type": "number"
                }
              }
            }
          },
          "stats": {
            "type": "object",
            "properties": {
              "mae": {
                "type": "object",
                "properties": {
                  "oneWk": {
                    "type": "number"
                  },
                  "twoWk": {
                    "type": "number"
                  },
                  "threeWk": {
                    "type": "number"
                  },
                  "fourWk": {
                    "type": "number"
                  }
                },
                "required": [
                  "oneWk",
                  "twoWk",
                  "threeWk",
                  "fourWk"
                ]
              },
              "log": {
                "type": "object",
                "properties": {
                  "oneWk": {
                    "type": "number"
                  },
                  "twoWk": {
                    "type": "number"
                  },
                  "threeWk": {
                    "type": "number"
                  },
                  "fourWk": {
                    "type": "number"
                  }
                },
                "required": [
                  "oneWk",
                  "twoWk",
                  "threeWk",
                  "fourWk"
                ]
              }
            },
            "required": [
              "mae",
              "log"
            ]
          }
        }
      }
    },
    "history": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "actual": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "items": {
              "required": [
                "week",
                "data"
              ],
              "properties": {
                "week": {
                  "type": "number"
                },
                "data": {
                  "type": "number"
                }
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "region",
    "observed",
    "actual",
    "baseline",
    "models",
    "history"
  ]
}

=== ThoughtfulMind/d3-foresight/examples/data-timechart.json
{"region":"US National","observed":[{"week":201630,"data":[{"lag":22,"value":0.719821},{"lag":21,"value":0.719821},{"lag":20,"value":0.719821},{"lag":19,"value":0.719821},{"lag":18,"value":0.719821},{"lag":17,"value":0.719821},{"lag":16,"value":0.719992},{"lag":15,"value":0.719992},{"lag":14,"value":0.720415},{"lag":13,"value":0.720415},{"lag":12,"value":0.720415},{"lag":11,"value":0.70946},{"lag":10,"value":0.70946},{"lag":9,"value":0.718529},{"lag":8,"value":0.747276},{"lag":7,"value":0.757904},{"lag":6,"value":0.758473},{"lag":5,"value":0.76113},{"lag":4,"value":0.771379},{"lag":3,"value":0.784216},{"lag":2,"value":0.797168},{"lag":1,"value":0.813631},{"lag":0,"value":0.892884}]},{"week":201631,"data":[{"lag":21,"value":0.666312},{"lag":20,"value":0.666312},{"lag":19,"value":0.666312},{"lag":18,"value":0.666312},{"lag":17,"value":0.666312},{"lag":16,"value":0.666312},{"lag":15,"value":0.666358},{"lag":14,"value":0.666358},{"lag":13,"value":0.667331},{"lag":12,"value":0.667331},{"lag":11,"value":0.667331},{"lag":10,"value":0.656261},{"lag":9,"value":0.656261},{"lag":8,"value":0.664653},{"lag":7,"value":0.690613},{"lag":6,"value":0.700123},{"lag":5,"value":0.706862},{"lag":4,"value":0.717635},{"lag":3,"value":0.711055},{"lag":2,"value":0.722401},{"lag":1,"value":0.743746},{"lag":0,"value":0.703335}]},{"week":201632,"data":[{"lag":20,"value":0.686179},{"lag":19,"value":0.686179},{"lag":18,"value":0.686179},{"lag":17,"value":0.686179},{"lag":16,"value":0.686179},{"lag":15,"value":0.686179},{"lag":14,"value":0.686273},{"lag":13,"value":0.686273},{"lag":12,"value":0.687033},{"lag":11,"value":0.687033},{"lag":10,"value":0.687024},{"lag":9,"value":0.682769},{"lag":8,"value":0.682769},{"lag":7,"value":0.688813},{"lag":6,"value":0.70765},{"lag":5,"value":0.710458},{"lag":4,"value":0.710586},{"lag":3,"value":0.723752},{"lag":2,"value":0.7157},{"lag":1,"value":0.721871},{"lag":0,"value":0.647381}]},{"week":201633,"data":[{"lag":19,"value":0.704238},{"lag":18,"value":0.704238},{"lag":17,"value":0.704238},{"lag":16,"value":0.704238},{"lag":15,"value":0.704238},{"lag":14,"value":0.704238},{"lag":13,"value":0.70431},{"lag":12,"value":0.70431},{"lag":11,"value":0.705526},{"lag":10,"value":0.705526},{"lag":9,"value":0.705561},{"lag":8,"value":0.702137},{"lag":7,"value":0.702137},{"lag":6,"value":0.709562},{"lag":5,"value":0.721153},{"lag":4,"value":0.718671},{"lag":3,"value":0.725069},{"lag":2,"value":0.744954},{"lag":1,"value":0.762361},{"lag":0,"value":0.645531}]},{"week":201634,"data":[{"lag":18,"value":0.823376},{"lag":17,"value":0.823376},{"lag":16,"value":0.823376},{"lag":15,"value":0.823376},{"lag":14,"value":0.823376},{"lag":13,"value":0.823376},{"lag":12,"value":0.823927},{"lag":11,"value":0.823927},{"lag":10,"value":0.825882},{"lag":9,"value":0.825882},{"lag":8,"value":0.826377},{"lag":7,"value":0.821178},{"lag":6,"value":0.821178},{"lag":5,"value":0.819987},{"lag":4,"value":0.832544},{"lag":3,"value":0.841089},{"lag":2,"value":0.852208},{"lag":1,"value":0.894368},{"lag":0,"value":0.919902}]},{"week":201635,"data":[{"lag":17,"value":0.990238},{"lag":16,"value":0.990238},{"lag":15,"value":0.990238},{"lag":14,"value":0.990238},{"lag":13,"value":0.990238},{"lag":12,"value":0.990238},{"lag":11,"value":0.990798},{"lag":10,"value":0.990798},{"lag":9,"value":0.993827},{"lag":8,"value":0.993827},{"lag":7,"value":0.994487},{"lag":6,"value":1.00636},{"lag":5,"value":1.00636},{"lag":4,"value":0.985291},{"lag":3,"value":1.00159},{"lag":2,"value":1.00723},{"lag":1,"value":1.02887},{"lag":0,"value":1.06314}]},{"week":201636,"data":[{"lag":16,"value":1.0138},{"lag":15,"value":1.0138},{"lag":14,"value":1.0138},{"lag":13,"value":1.0138},{"lag":12,"value":1.0138},{"lag":11,"value":1.0138},{"lag":10,"value":1.01666},{"lag":9,"value":1.01666},{"lag":8,"value":1.01764},{"lag":7,"value":1.01764},{"lag":6,"value":1.01909},{"lag":5,"value":1.01322},{"lag":4,"value":1.01322},{"lag":3,"value":1.02014},{"lag":2,"value":1.04315},{"lag":1,"value":1.04317},{"lag":0,"value":1.00415}]},{"week":201637,"data":[{"lag":15,"value":1.07203},{"lag":14,"value":1.07203},{"lag":13,"value":1.07203},{"lag":12,"value":1.07203},{"lag":11,"value":1.07203},{"lag":10,"value":1.07203},{"lag":9,"value":1.07693},{"lag":8,"value":1.07693},{"lag":7,"value":1.08008},{"lag":6,"value":1.08008},{"lag":5,"value":1.06632},{"lag":4,"value":1.05972},{"lag":3,"value":1.05972},{"lag":2,"value":1.08548},{"lag":1,"value":1.11045},{"lag":0,"value":1.01608}]},{"week":201638,"data":[{"lag":14,"value":1.10439},{"lag":13,"value":1.10439},{"lag":12,"value":1.10439},{"lag":11,"value":1.10439},{"lag":10,"value":1.10439},{"lag":9,"value":1.10439},{"lag":8,"value":1.10989},{"lag":7,"value":1.10989},{"lag":6,"value":1.10637},{"lag":5,"value":1.10637},{"lag":4,"value":1.09019},{"lag":3,"value":1.09764},{"lag":2,"value":1.09764},{"lag":1,"value":1.13573},{"lag":0,"value":1.25346}]},{"week":201639,"data":[{"lag":13,"value":1.19951},{"lag":12,"value":1.19951},{"lag":11,"value":1.19951},{"lag":10,"value":1.19951},{"lag":9,"value":1.19951},{"lag":8,"value":1.19951},{"lag":7,"value":1.20474},{"lag":6,"value":1.20474},{"lag":5,"value":1.19999},{"lag":4,"value":1.19999},{"lag":3,"value":1.17174},{"lag":2,"value":1.19803},{"lag":1,"value":1.19803},{"lag":0,"value":1.25959}]},{"week":201640,"data":[{"lag":12,"value":1.20663},{"lag":11,"value":1.20739},{"lag":10,"value":1.20739},{"lag":9,"value":1.21418},{"lag":8,"value":1.2222},{"lag":7,"value":1.2039},{"lag":6,"value":1.20959},{"lag":5,"value":1.21025},{"lag":4,"value":1.20947},{"lag":3,"value":1.20649},{"lag":2,"value":1.19698},{"lag":1,"value":1.1988},{"lag":0,"value":1.09511}]},{"week":201641,"data":[{"lag":11,"value":1.24765},{"lag":10,"value":1.24905},{"lag":9,"value":1.24862},{"lag":8,"value":1.25141},{"lag":7,"value":1.26439},{"lag":6,"value":1.24698},{"lag":5,"value":1.25598},{"lag":4,"value":1.26423},{"lag":3,"value":1.2343},{"lag":2,"value":1.23613},{"lag":1,"value":1.23232},{"lag":0,"value":1.19788}]},{"week":201642,"data":[{"lag":10,"value":1.28073},{"lag":9,"value":1.28271},{"lag":8,"value":1.28461},{"lag":7,"value":1.28683},{"lag":6,"value":1.30693},{"lag":5,"value":1.28713},{"lag":4,"value":1.29255},{"lag":3,"value":1.29631},{"lag":2,"value":1.27541},{"lag":1,"value":1.28702},{"lag":0,"value":1.28869}]},{"week":201643,"data":[{"lag":9,"value":1.36925},{"lag":8,"value":1.37273},{"lag":7,"value":1.37303},{"lag":6,"value":1.37336},{"lag":5,"value":1.39631},{"lag":4,"value":1.38025},{"lag":3,"value":1.34601},{"lag":2,"value":1.3762},{"lag":1,"value":1.34104},{"lag":0,"value":1.30927}]},{"week":201644,"data":[{"lag":8,"value":1.49578},{"lag":7,"value":1.49717},{"lag":6,"value":1.49447},{"lag":5,"value":1.5018},{"lag":4,"value":1.50889},{"lag":3,"value":1.51606},{"lag":2,"value":1.4624},{"lag":1,"value":1.50385},{"lag":0,"value":1.37269}]},{"week":201645,"data":[{"lag":7,"value":1.57873},{"lag":6,"value":1.57955},{"lag":5,"value":1.57823},{"lag":4,"value":1.56858},{"lag":3,"value":1.59778},{"lag":2,"value":1.58989},{"lag":1,"value":1.52294},{"lag":0,"value":1.55806}]},{"week":201646,"data":[{"lag":6,"value":1.67521},{"lag":5,"value":1.67721},{"lag":4,"value":1.66999},{"lag":3,"value":1.66575},{"lag":2,"value":1.69192},{"lag":1,"value":1.63108},{"lag":0,"value":1.60446}]},{"week":201647,"data":[{"lag":5,"value":1.94098},{"lag":4,"value":1.94575},{"lag":3,"value":1.93924},{"lag":2,"value":1.92829},{"lag":1,"value":1.94245},{"lag":0,"value":1.8029}]},{"week":201648,"data":[{"lag":4,"value":1.8506},{"lag":3,"value":1.85861},{"lag":2,"value":1.85192},{"lag":1,"value":1.86137},{"lag":0,"value":1.76578}]},{"week":201649,"data":[{"lag":3,"value":1.98134},{"lag":2,"value":2.01039},{"lag":1,"value":2.00131},{"lag":0,"value":1.9479}]},{"week":201650,"data":[{"lag":2,"value":2.22249},{"lag":1,"value":2.30488},{"lag":0,"value":2.31662}]},{"week":201651,"data":[{"lag":1,"value":2.73092},{"lag":0,"value":2.89491}]},{"week":201652,"data":[{"lag":0,"value":3.35011}]},{"week":201701,"data":[]},{"week":201702,"data":[]},{"week":201703,"data":[]},{"week":201704,"data":[]},{"week":201705,"data":[]},{"week":201706,"data":[]},{"week":201707,"data":[]},{"week":201708,"data":[]},{"week":201709,"data":[]},{"week":201710,"data":[]},{"week":201711,"data":[]},{"week":201712,"data":[]},{"week":201713,"data":[]},{"week":201714,"data":[]},{"week":201715,"data":[]},{"week":201716,"data":[]},{"week":201717,"data":[]},{"week":201718,"data":[]},{"week":201719,"data":[]},{"week":201720,"data":[]},{"week":201721,"data":[]},{"week":201722,"data":[]},{"week":201723,"data":[]},{"week":201724,"data":[]},{"week":201725,"data":[]},{"week":201726,"data":[]},{"week":201727,"data":[]},{"week":201728,"data":[]},{"week":201729,"data":[]}],"actual":[{"week":201630,"data":0.719821},{"week":201631,"data":0.666312},{"week":201632,"data":0.686179},{"week":201633,"data":0.704238},{"week":201634,"data":0.823376},{"week":201635,"data":0.990238},{"week":201636,"data":1.0138},{"week":201637,"data":1.07203},{"week":201638,"data":1.10439},{"week":201639,"data":1.19951},{"week":201640,"data":1.20663},{"week":201641,"data":1.24765},{"week":201642,"data":1.28073},{"week":201643,"data":1.36925},{"week":201644,"data":1.49578},{"week":201645,"data":1.57873},{"week":201646,"data":1.67521},{"week":201647,"data":1.94098},{"week":201648,"data":1.8506},{"week":201649,"data":1.98134},{"week":201650,"data":2.22249},{"week":201651,"data":2.73092},{"week":201652,"data":3.35011},{"week":201701,"data":-1},{"week":201702,"data":-1},{"week":201703,"data":-1},{"week":201704,"data":-1},{"week":201705,"data":-1},{"week":201706,"data":-1},{"week":201707,"data":-1},{"week":201708,"data":-1},{"week":201709,"data":-1},{"week":201710,"data":-1},{"week":201711,"data":-1},{"week":201712,"data":-1},{"week":201713,"data":-1},{"week":201714,"data":-1},{"week":201715,"data":-1},{"week":201716,"data":-1},{"week":201717,"data":-1},{"week":201718,"data":-1},{"week":201719,"data":-1},{"week":201720,"data":-1},{"week":201721,"data":-1},{
